import Head from 'next/head';
import Image from 'next/image';
import { useSession, signOut } from 'next-auth/react';
import { useRouter } from 'next/router';

import styles from '../styles/Home.module.css';
import { useEffect } from 'react';

export default function Home() {
	const router = useRouter();
	const { data: session } = useSession();

	useEffect(() => {
		if (!session) {
			router.replace('/auth');
		}
	}, [session]);

	if (session) {
		return (
			<div className={ styles.container }>
				<Head>
					<title>Zapps</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className={ styles.main }>
					{ session?.user?.image && <img src={ session?.user?.image } height='100px' className='rounded-full' /> }
					<div className='h-8'></div>
					<h1 className={ styles.title }>
						Welcome { session?.user?.name }
					</h1>

					<p className={ `cursor-pointer ${ styles.description }` }
						onClick={ () => signOut() }
					>
						Logout
					</p>

				</main>

				<footer className={ styles.footer }>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by Zapps
					</a>
				</footer>
			</div>
		);
	} return null;
}
